# Generated by Django 6.0.6 on 2026-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemsetting_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sale_manager', 'Sales Manager'), ('worker', 'Worker'), ('supplier', 'Supplier')], db_index=True, default='worker', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
